In [1]:
from collections import OrderedDict

import numpy as np
import pandas as pd

import pylogit as pl

import seaborn as sbn
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Load the data
train_df_all =\
    pd.read_csv('./data/mnl_training_data_long_all_sample.csv')

In [3]:
# Create needed columns
for df in [train_df_all]:
    df['num_adults_eq_2'] = (df['num_adults'] == 2).astype(int)
    df['num_adults_gte_3'] = (df['num_adults'] >= 3).astype(int)
    df['sectr_1'] = (df['sectr'] == 1).astype(int)
    df['sectr_2'] = (df['sectr'] == 2).astype(int)
    df['income_1'] = (df['incom'] == 1).astype(int)
    df['income_2'] = (df['incom'] == 2).astype(int)
    df['income_4'] = (df['incom'] == 4).astype(int)
    df['income_5'] = (df['incom'] == 5).astype(int)
    df['income_gt_5'] = (df['incom'] > 5).astype(int)

In [4]:
# Create labels for the various alternatives
choice_labels =\
    {1: '0 Cars',
     2: '1 Car',
     3: '2 Cars',
     4: '3+ Cars',
    }

# Create the specification dictionaries
spec_dict, name_dict = OrderedDict(), OrderedDict()

spec_dict['intercept'] = [2, 3, 4]
spec_dict['num_adults_eq_2'] = [1, 2, 4]
spec_dict['num_adults_gte_3'] = [1, 2, 3]
spec_dict['sectr_1'] = [2, 3, 4]
spec_dict['sectr_2'] = [2, 3, 4]
spec_dict['income_1'] = [2, 3, 4]
spec_dict['income_2'] = [2, 3, 4]
spec_dict['income_4'] = [2, 3, 4]
spec_dict['income_5'] = [2, 3, 4]
spec_dict['income_gt_5'] = [2, 3, 4]
spec_dict['tran_access'] = [2, 3, 4]
spec_dict['numWorkers'] = [2, 3, 4]

for col in spec_dict:
    name_dict[col] =\
        [col + ' ({})'.format(choice_labels[x]) for x in spec_dict[col]]

In [5]:
# Take note of important data columns
ALT_ID_COL = 'altid'
CHOICE_COL = 'choiceBoolean'
OBS_ID_COL = 'sampn'

# Create the model object
mnl_model =\
    pl.create_choice_model(train_df_all,
                           ALT_ID_COL,
                           OBS_ID_COL,
                           CHOICE_COL,
                           spec_dict,
                           'MNL',
                           names=name_dict,
                          )

/Users/tbrathwaite/anaconda2/lib/python2.7/site-packages/pylogit/choice_tools.py:703: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  design_matrix = np.hstack((x[:, None] for x in independent_vars))

In [6]:
# Fit the model
num_params_mnl = mnl_model.design.shape[1]
init_values = np.zeros(num_params_mnl)

mnl_model.fit_mle(init_values)

# Show model estimation results
mnl_model.get_statsmodels_summary()

Log-likelihood at zero: -14,528.3649
Initial Log-likelihood: -14,528.3649

/Users/tbrathwaite/anaconda2/lib/python2.7/site-packages/scipy/optimize/_minimize.py:506: RuntimeWarning: Method BFGS does not use Hessian information (hess).
  RuntimeWarning)

Estimation Time for Point Estimation: 0.55 seconds.
Final log-likelihood: -8,419.3714

<class 'statsmodels.iolib.summary.Summary'>
"""
                     Multinomial Logit Model Regression Results
===================================================================================
Dep. Variable:               choiceBoolean   No. Observations:               10,480
Model:             Multinomial Logit Model   Df Residuals:                   10,444
Method:                                MLE   Df Model:                           36
Date:                     Mon, 13 Jan 2020   Pseudo R-squ.:                   0.420
Time:                             07:44:11   Pseudo R-bar-squ.:               0.418
AIC:                            16,910.743   Log-Likelihood:             -8,419.371
BIC:                            17,172.003   LL-Null:                   -14,528.365
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
intercept (1 Car)             2.6264      0.255     10.311      0.000       2.127       3.126
intercept (2 Cars)            1.0124      0.469      2.159      0.031       0.093       1.931
intercept (3+ Cars)          -1.9606      1.221     -1.606      0.108      -4.353       0.432
num_adults_eq_2 (0 Cars)     -3.4084      0.331    -10.288      0.000      -4.058      -2.759
num_adults_eq_2 (1 Car)      -3.0713      0.327     -9.400      0.000      -3.712      -2.431
num_adults_eq_2 (3+ Cars)    -1.8843      1.065     -1.769      0.077      -3.973       0.204
num_adults_gte_3 (0 Cars)    -3.8212      1.022     -3.740      0.000      -5.824      -1.819
num_adults_gte_3 (1 Car)     -3.6161      1.019     -3.549      0.000      -5.613      -1.619
num_adults_gte_3 (2 Cars)    -0.5120      1.063     -0.482      0.630      -2.596       1.572
sectr_1 (1 Car)               0.5661      0.092      6.138      0.000       0.385       0.747
sectr_1 (2 Cars)              0.2848      0.156      1.831      0.067      -0.020       0.590
sectr_1 (3+ Cars)             0.6836      0.305      2.239      0.025       0.085       1.282
sectr_2 (1 Car)              -1.5095      0.064    -23.608      0.000      -1.635      -1.384
sectr_2 (2 Cars)             -2.9781      0.128    -23.285      0.000      -3.229      -2.727
sectr_2 (3+ Cars)            -3.2721      0.387     -8.456      0.000      -4.031      -2.514
income_1 (1 Car)             -1.8959      0.097    -19.483      0.000      -2.087      -1.705
income_1 (2 Cars)            -3.5720      0.359     -9.959      0.000      -4.275      -2.869
income_1 (3+ Cars)           -3.5108      1.047     -3.352      0.001      -5.563      -1.458
income_2 (1 Car)             -0.9951      0.071    -14.090      0.000      -1.134      -0.857
income_2 (2 Cars)            -1.7182      0.135    -12.737      0.000      -1.983      -1.454
income_2 (3+ Cars)           -2.2863      0.439     -5.205      0.000      -3.147      -1.425
income_4 (1 Car)              0.7917      0.106      7.469      0.000       0.584       0.999
income_4 (2 Cars)             1.5112      0.123     12.328      0.000       1.271       1.751
income_4 (3+ Cars)            1.8265      0.246      7.423      0.000       1.344       2.309
income_5 (1 Car)              1.3261      0.209      6.343      0.000       0.916       1.736
income_5 (2 Cars)             3.1611      0.215     14.737      0.000       2.741       3.582
income_5 (3+ Cars)            3.8959      0.297     13.112      0.000       3.314       4.478
income_gt_5 (1 Car)          -0.2626      0.089     -2.961      0.003      -0.436      -0.089
income_gt_5 (2 Cars)          0.2713      0.118      2.295      0.022       0.040       0.503
income_gt_5 (3+ Cars)         0.7713      0.274      2.817      0.005       0.235       1.308
tran_access (1 Car)          -0.3569      0.038     -9.512      0.000      -0.430      -0.283
tran_access (2 Cars)         -0.8650      0.054    -15.964      0.000      -0.971      -0.759
tran_access (3+ Cars)        -0.8694      0.114     -7.635      0.000      -1.093      -0.646
numWorkers (1 Car)            0.3593      0.036      9.897      0.000       0.288       0.430
numWorkers (2 Cars)           0.7613      0.050     15.102      0.000       0.663       0.860
numWorkers (3+ Cars)          1.1392      0.084     13.540      0.000       0.974       1.304
=============================================================================================
"""

In [7]:
# This cell is just to confirm how to get the predicted
# probabilities used by the authors.
mnl_wide_probs = np.reshape(mnl_model.long_fitted_probs, (-1, 4))
mnl_wide_probs

array([[8.12080728e-01, 1.87623344e-01, 2.74805223e-04, 2.11221648e-05],
       [8.68041140e-01, 1.31834072e-01, 1.18548005e-04, 6.23981297e-06],
       [4.91126611e-01, 4.60898168e-01, 4.76778682e-02, 2.97353076e-04],
       ...,
       [1.01039883e-01, 5.63471733e-01, 3.30157255e-01, 5.33112997e-03],
       [9.74283093e-02, 5.84566617e-01, 3.14733687e-01, 3.27138729e-03],
       [1.01039883e-01, 5.63471733e-01, 3.30157255e-01, 5.33112997e-03]])

In [8]:
mnl_prob_orig = pd.read_csv("mnl_prob_all.csv")
mnl_prob_orig[['sampn', 'X11', 'X2', 'X3', 'X4']].head()

   sampn       X11        X2        X3        X4
0  14416  0.812081  0.187623  0.000275  0.000021
1  14418  0.868041  0.131834  0.000119  0.000006
2  14425  0.491127  0.460898  0.047678  0.000297
3  14426  0.141796  0.567249  0.231473  0.059481
4  14432  0.301705  0.529700  0.165594  0.003001

In [9]:
mnl_prob_orig[['sampn', 'X11', 'X2', 'X3', 'X4']].tail()

        sampn       X11        X2        X3        X4
10475  176334  0.490953  0.504416  0.004448  0.000184
10476  176335  0.101040  0.563472  0.330157  0.005331
10477  176336  0.101040  0.563472  0.330157  0.005331
10478  176337  0.097428  0.584567  0.314734  0.003271
10479  176338  0.101040  0.563472  0.330157  0.005331